/* @bruin
name: analytics_504624180.ga4_EcommercePurchases_504624180
type: bq.sql
description: |
  GA4 ecommerce purchases report view. Contains item-level purchase data including
  product details, revenue, and funnel metrics. View over p_ga4_EcommercePurchases_504624180.

materialization:
  type: view

columns:
  - name: itemBrand
    type: STRING
    description: Brand name of the purchased item
  - name: itemCategory
    type: STRING
    description: Primary category of the item
  - name: itemCategory2
    type: STRING
    description: Secondary category level
  - name: itemCategory3
    type: STRING
    description: Tertiary category level
  - name: itemCategory4
    type: STRING
    description: Fourth category level
  - name: itemCategory5
    type: STRING
    description: Fifth category level
  - name: itemId
    type: STRING
    description: Unique identifier for the item (SKU)
  - name: itemListPosition
    type: STRING
    description: Position of the item in a product list
  - name: itemName
    type: STRING
    description: Display name of the item
  - name: itemVariant
    type: STRING
    description: Item variant (e.g., size, color)
  - name: itemRevenue
    type: FLOAT
    description: Total revenue generated by this item
  - name: itemsAddedToCart
    type: INTEGER
    description: Number of times this item was added to cart
  - name: itemsPurchased
    type: INTEGER
    description: Number of units purchased
  - name: itemsViewed
    type: INTEGER
    description: Number of times this item was viewed
  - name: _LATEST_DATE
    type: DATE
    description: Most recent date of data refresh
  - name: _DATA_DATE
    type: DATE
    description: Date partition of the data
@bruin */

SELECT
  *,
  DATE('2026-01-10') AS _LATEST_DATE,
  DATE(_PARTITIONTIME) AS _DATA_DATE
FROM `alpaka03sept25.analytics_504624180.p_ga4_EcommercePurchases_504624180`
